---
title: "Gastric Cancer"
author: "Matt Bixley"
date: "09/10/2020"
output: 
  html_document: 
    toc: yes
    toc_float: true
    theme: cerulean
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gt)
data <- read_csv("data/tcga_gastric_cancer_data.csv")

```

```{r palette}
library(Manu)
scale_color <- get_pal("Kaka")
print_pal(scale_color)
```


# Glimpse

```{r}
data %>% 
  glimpse()
```
```{r tidy}
data <- data %>% 
  select(id, MolecularSubtype, LaurenClass, HPylori, CDH1mutation, CDH1expression, EMTmetagene)
  
data %>% 
  head() %>% 
  gt()
```


# Tables
```{r table}
data_sum <- data %>% 
  group_by(LaurenClass) %>% 
  summarise(meanCDH1 = mean(CDH1expression, na.rm = T), meanEMT = mean(EMTmetagene, na.rm=T)) 

data_count <- data %>% 
  group_by(LaurenClass) %>% 
  count()

left_join(data_sum, data_count) %>% 
  gt() %>% 
  tab_style(
    style = list(
      cell_borders(
        sides = "bottom",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_column_labels(
        columns = gt::everything()
      )
    )
  )
```



# Plots
```{r}
# selecting character variables
data_char <- data %>% 
    select_if(is.character)

# setting a named vector
names <- names(data_char)
names <- set_names(names[-1])
names
```
```{r plot}
data %>% 
    count(LaurenClass) %>% 
    mutate(prop = n/sum(n)) %>%
    mutate(prop = round(prop, 2)) %>% 
    filter(LaurenClass != "NA") %>% 
    ggplot(aes(x = fct_reorder(LaurenClass, prop),
               y = prop,
               color = LaurenClass)) +
    scale_colour_manual(values = scale_color) +
    geom_segment(aes(xend = LaurenClass, yend = 0), show.legend = F) +
    geom_point(aes(size = prop), show.legend = F) +
    geom_label(aes(label = prop, size = prop*10), 
               fill = "white", hjust = "inward", show.legend = F) +
    labs(x = "LaurenClass") +
    coord_flip() +
    theme_bw()
```


```{r plotfunction}
# second: plot_function
plot_frequency <- function(x) {
    data %>% 
        count(.data[[x]]) %>% 
        mutate(prop = n/sum(n)) %>% 
        mutate(prop = round(prop, 2)) %>% 
        filter(.data[[x]] != "NA") %>% 
        ggplot(aes(x = fct_reorder(.data[[x]], prop),y = prop, color = .data[[x]])) +
        scale_colour_manual(values = scale_color) +
        geom_segment(aes(xend = .data[[x]], yend = 0), show.legend = F) +
        geom_point(aes(size = prop), show.legend = F) +
        geom_label(aes(label = prop, size = prop*10), 
                   fill = "white", hjust = "inward",show.legend = F) +
        labs(x = x) +
        coord_flip() +
        theme_bw()
}
```

```{r allplots}
all_plots <- map(names, plot_frequency)
cowplot::plot_grid(plotlist = all_plots, ncol =1)
```

# Models

Can expression and other variable predicit lauren class

```{r models}
data_mod <- data %>% 
  filter(!is.na(LaurenClass)) %>% 
  mutate_if(is.character, factor)

mod <- lm(LaurenClass ~ CDH1expression, data = data_mod)

```

